table 'LEFT JOIN'
	lineageTag: 1e8dc9b0-b167-407c-a7b6-35cc55c3966d

	column ID_CLIENTE
		dataType: string
		lineageTag: d4d33d18-aa86-4443-bd9b-0dd3b83968d4
		summarizeBy: none
		sourceColumn: ID_CLIENTE

		annotation SummarizationSetBy = Automatic

	column MARCA
		dataType: string
		lineageTag: cf5a2632-fa17-4039-ba50-9a28024be96a
		summarizeBy: none
		sourceColumn: MARCA

		annotation SummarizationSetBy = Automatic

	column MODELO
		dataType: string
		lineageTag: 7792552e-ada3-4c2a-9f01-b40600fd647f
		summarizeBy: none
		sourceColumn: MODELO

		annotation SummarizationSetBy = Automatic

	column PLACA
		dataType: string
		lineageTag: a6b3a558-0588-4a2e-b100-2abc7436d16e
		summarizeBy: none
		sourceColumn: PLACA

		annotation SummarizationSetBy = Automatic

	column KILOMETRO_PERCORRIDO
		dataType: double
		lineageTag: 20d7d242-441f-4c46-81cf-75f5fb9cfc48
		summarizeBy: sum
		sourceColumn: KILOMETRO_PERCORRIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb3ba40b-cee5-4882-92ef-11e45a7022ff
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: 0c282499-7498-4862-96fc-c0ad695019f9
			defaultHierarchy: LocalDateTable_24904d83-f970-45a9-a0b3-31861db1c1ae.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'VALOR POR KM'
		dataType: double
		lineageTag: 9a0707bf-f651-4c6e-8a57-4becd73a0cbb
		summarizeBy: sum
		sourceColumn: VALOR POR KM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SITUAÇÃO CADASTRAL'
		dataType: string
		lineageTag: a908f8a6-19e6-4421-92c6-1b0e5b633d46
		summarizeBy: none
		sourceColumn: SITUAÇÃO CADASTRAL

		annotation SummarizationSetBy = Automatic

	column ANO
		dataType: string
		lineageTag: 7368e03e-28cb-4986-916b-f0da9623431b
		summarizeBy: none
		sourceColumn: ANO

		annotation SummarizationSetBy = Automatic

	column MÊS
		dataType: string
		lineageTag: edf9f13e-9c98-4aa6-83ec-6e2600bb26d6
		summarizeBy: none
		sourceColumn: MÊS

		annotation SummarizationSetBy = Automatic

	column DIA
		dataType: string
		lineageTag: ba35bb9f-f889-45af-b9a1-4d25b42fa187
		summarizeBy: none
		sourceColumn: DIA

		annotation SummarizationSetBy = Automatic

	column 'FAT MEDIDA'
		dataType: double
		lineageTag: baec9cab-0cea-48a0-891a-0855731381d4
		summarizeBy: sum
		sourceColumn: FAT MEDIDA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NomeDoDia
		dataType: string
		lineageTag: 9a3aae92-4ae0-4512-8f74-5c568520f619
		summarizeBy: none
		sourceColumn: NomeDoDia

		annotation SummarizationSetBy = Automatic

	column 'tb_cli.ID'
		dataType: string
		lineageTag: d0e9931d-a6b0-447a-a99f-15f8c704bca7
		summarizeBy: none
		sourceColumn: tb_cli.ID

		annotation SummarizationSetBy = Automatic

	column 'tb_cli.NOME'
		dataType: string
		lineageTag: 236250fc-e957-46b4-a9e4-b5556d65b7db
		summarizeBy: none
		sourceColumn: tb_cli.NOME

		annotation SummarizationSetBy = Automatic

	column 'tb_cli.CIDADE'
		dataType: string
		lineageTag: 0c2e931d-1a10-47c6-9582-0d8d368343c6
		summarizeBy: none
		sourceColumn: tb_cli.CIDADE

		annotation SummarizationSetBy = Automatic

	partition 'LEFT JOIN' = m
		mode: import
		source =
				let
				    Fonte = Table.NestedJoin(tb_km, {"ID_CLIENTE"}, tb_cli, {"ID"}, "tb_cli", JoinKind.LeftOuter),
				    #"tb_cli Expandido" = Table.ExpandTableColumn(Fonte, "tb_cli", {"ID", "NOME", "CIDADE"}, {"tb_cli.ID", "tb_cli.NOME", "tb_cli.CIDADE"})
				in
				    #"tb_cli Expandido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

