table MEDIDAS
	lineageTag: c0e0ede5-8e0a-4306-9354-06c8dc8be18d

	measure 'Medida KM' = AVERAGE(tb_km[KILOMETRO_PERCORRIDO])
		lineageTag: 70a6423c-0b36-46b7-ba68-0feb244f1f6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD CLIENTES' = DISTINCTCOUNT(tb_cli[ID])
		formatString: 0
		lineageTag: a0e65b75-ead5-4621-9bca-16b9b867babf

	measure 'TT CIDADES' = DISTINCTCOUNT(tb_cli[CIDADE])
		formatString: 0
		lineageTag: 0c637e04-c8b3-4f6c-b3da-3e18f836dcc5

	measure 'MED SALARIO CLI' = SUM(tb_cli[SALARIO]) / DISTINCTCOUNT(tb_cli[ID])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: db61695a-cff4-4512-b2c1-a8f5c93fff80

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure FATURAMENTO = SUMX(tb_km, tb_km[VALOR POR KM] * tb_km[KILOMETRO_PERCORRIDO])
		lineageTag: 47e08896-b151-465b-97d5-8cb98cd4557f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TicketMédioPorCliente =
			
			DIVIDE(
			    SUM(tb_km[FAT MEDIDA]),
			    DISTINCTCOUNT(tb_km[ID_CLIENTE]),
			    0
			)
		lineageTag: 87aa1adc-5261-444a-91b2-2e877849deb7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition MEDIDAS = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

